name: Test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with token
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Checkout without token
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build Test
        run: docker buildx build --load --tag test:test --file ./Dockerfile ./

      - name: Version
        if: github.event_name != 'pull_request'
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 17.4
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
